import { StyleSheet } from "react-native";
import { SHADOWS, COLORS, SIZES, FONTS } from "../../utils/AppTheme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    padding: SIZES.padding.lg,
  },
  modeBadge: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: COLORS.primary + '10',
  paddingHorizontal: 8,
  paddingVertical: 4,
  borderRadius: 12,
  alignSelf: 'flex-start',
  marginTop: 4,
},
modeText: {
  fontSize: 12,
  color: COLORS.primary,
  marginLeft: 4,
  fontWeight: '500',
},
  header: {
    backgroundColor: COLORS.primary,
    padding: SIZES.padding.lg,
    borderRadius: SIZES.radius.lg,
    alignItems: "center",
    marginBottom: SIZES.margin.lg,
    position: "relative",
    ...SHADOWS.md,
  },
  backBtn: {
    position: "absolute",
    left: SIZES.padding.lg,
    top: SIZES.padding.lg,
  },
  clearBtn: {
    position: "absolute",
    right: SIZES.padding.lg,
    top: SIZES.padding.lg,
    backgroundColor: COLORS.primaryDark,
    padding: SIZES.padding.xs,
    borderRadius: SIZES.radius.full,
  },
  headerTitle: {
    ...FONTS.h4,
    color: COLORS.white,
    marginTop: SIZES.margin.sm,
  },
  headerSubtitle: {
    ...FONTS.bodySmall,
    color: COLORS.white,
    marginTop: SIZES.margin.xs,
  },
  section: {
    backgroundColor: COLORS.white,
    borderRadius: SIZES.radius.lg,
    padding: SIZES.padding.lg,
    marginBottom: SIZES.margin.lg,
    ...SHADOWS.sm,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  lockedSection: {
    opacity: 0.7,
    backgroundColor: COLORS.inputBackground,
  },
  sectionHeader: {
    marginBottom: SIZES.margin.md,
  },
  sectionTitle: {
    ...FONTS.h5,
    color: COLORS.textPrimary,
  },
  lockedTitle: {
    color: COLORS.textSecondary,
  },
  lockedMessage: {
    ...FONTS.caption,
    color: COLORS.warning,
    marginTop: SIZES.margin.xs,
    fontStyle: "italic",
  },
  optionalNote: {
    ...FONTS.caption,
    color: COLORS.textSecondary,
    fontStyle: "italic",
    marginBottom: SIZES.margin.md,
  },
  inputGroup: {
    marginBottom: SIZES.margin.md,
  },
  label: {
    ...FONTS.label,
    color: COLORS.textPrimary,
    marginBottom: SIZES.margin.xs,
  },
  disabledLabel: {
    color: COLORS.textSecondary,
  },
  input: {
    height: SIZES.input.height,
    backgroundColor: COLORS.inputBackground,
    borderRadius: SIZES.radius.md,
    paddingHorizontal: SIZES.padding.md,
    justifyContent: "center",
    ...FONTS.body,
    color: COLORS.textPrimary,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  disabledInput: {
    backgroundColor: COLORS.inputBackground,
    borderColor: COLORS.borderLight,
    opacity: 0.7,
  },
  errorInput: {
    borderColor: COLORS.error,
    borderWidth: 2,
  },
  verifiedInput: {
    borderColor: COLORS.success,
    backgroundColor: COLORS.successLight,
  },
  pendingInput: {
    borderColor: COLORS.warning,
    backgroundColor: COLORS.warningLight,
  },
  dateText: {
    ...FONTS.body,
    color: COLORS.textPrimary,
    flex: 1,
  },
  placeholderText: {
    ...FONTS.body,
    color: COLORS.inputPlaceholder,
    flex: 1,
  },
  disabledText: {
    color: COLORS.inputPlaceholderDisabled,
  },
  dateIcon: {
    marginLeft: SIZES.margin.sm,
  },
  checkboxContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: SIZES.margin.xs,
  },
  checkbox: {
    flex: 1,
    height: SIZES.input.height,
    backgroundColor: COLORS.inputBackground,
    borderRadius: SIZES.radius.md,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: SIZES.margin.xs,
  },
  disabledCheckbox: {
    backgroundColor: COLORS.inputBackground,
    borderColor: COLORS.borderLight,
    opacity: 0.7,
  },
  checkboxSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primaryDark,
  },
  checkboxText: {
    ...FONTS.body,
    color: COLORS.textSecondary,
  },
  checkboxTextSelected: {
    color: COLORS.white,
    fontWeight: "600",
  },
  mobileInput: {
    flexDirection: "row",
    alignItems: "center",
    height: SIZES.input.height,
    backgroundColor: COLORS.inputBackground,
    borderRadius: SIZES.radius.md,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    paddingHorizontal: SIZES.padding.md,
  },
  countryCode: {
    ...FONTS.h6,
    color: COLORS.primary,
    marginRight: SIZES.margin.sm,
  },
  mobileField: {
    flex: 1,
    ...FONTS.body,
    color: COLORS.textPrimary,
  },
  errorText: {
    ...FONTS.caption,
    color: COLORS.error,
    marginTop: SIZES.margin.xs,
  },
  loadingText: {
    ...FONTS.caption,
    color: COLORS.info,
    marginTop: SIZES.margin.xs,
    fontStyle: "italic",
  },
  confirmBtn: {
    backgroundColor: COLORS.primary,
    height: SIZES.button.lg,
    borderRadius: SIZES.radius.lg,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: SIZES.margin.xl,
    ...SHADOWS.md,
  },
  confirmBtnDisabled: {
    backgroundColor: COLORS.disabled,
  },
  confirmText: {
    ...FONTS.button,
    color: COLORS.white,
  },
  // Aadhaar specific styles
  aadhaarHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SIZES.margin.xs,
  },
  aadhaarContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  aadhaarInput: {
    flex: 1,
    marginRight: SIZES.margin.sm,
  },
  aadhaarActions: {
    flexDirection: "row",
  },
  aadhaarButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SIZES.padding.sm,
    paddingVertical: SIZES.padding.xs,
    borderRadius: SIZES.radius.sm,
    marginLeft: SIZES.margin.xs,
  },
  viewDetailsButton: {
    backgroundColor: COLORS.infoLight,
    borderWidth: 1,
    borderColor: COLORS.info,
  },
  viewDetailsText: {
    ...FONTS.caption,
    color: COLORS.info,
    marginLeft: 4,
    fontWeight: "600",
  },
  clearButton: {
    backgroundColor: COLORS.errorLight,
    borderWidth: 1,
    borderColor: COLORS.error,
  },
  clearText: {
    ...FONTS.caption,
    color: COLORS.error,
    marginLeft: 4,
    fontWeight: "600",
  },
  verifyButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.primary,
    paddingHorizontal: SIZES.padding.md,
    paddingVertical: SIZES.padding.sm,
    borderRadius: SIZES.radius.md,
    minHeight: SIZES.input.height,
    justifyContent: "center",
    minWidth: 100,
  },
  verifyButtonDisabled: {
    backgroundColor: COLORS.disabled,
  },
  verifyButtonText: {
    ...FONTS.bodySmall,
    color: COLORS.white,
    marginLeft: SIZES.margin.xs,
    fontWeight: "600",
  },
  pendingButton: {
    backgroundColor: COLORS.warning,
  },
  verifiedBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.successLight,
    paddingHorizontal: SIZES.padding.sm,
    paddingVertical: 4,
    borderRadius: SIZES.radius.sm,
    borderWidth: 1,
    borderColor: COLORS.success,
  },
  verifiedText: {
    ...FONTS.caption,
    color: COLORS.success,
    marginLeft: 4,
    fontWeight: "600",
  },
  pendingBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.warningLight,
    paddingHorizontal: SIZES.padding.sm,
    paddingVertical: 4,
    borderRadius: SIZES.radius.sm,
    borderWidth: 1,
    borderColor: COLORS.warning,
  },
  pendingText: {
    ...FONTS.caption,
    color: COLORS.warning,
    marginLeft: 4,
    fontWeight: "600",
  },
  failedBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.errorLight,
    paddingHorizontal: SIZES.padding.sm,
    paddingVertical: 4,
    borderRadius: SIZES.radius.sm,
    borderWidth: 1,
    borderColor: COLORS.error,
  },
  failedText: {
    ...FONTS.caption,
    color: COLORS.error,
    marginLeft: 4,
    fontWeight: "600",
  },
  initiatedBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.infoLight,
    paddingHorizontal: SIZES.padding.sm,
    paddingVertical: 4,
    borderRadius: SIZES.radius.sm,
    borderWidth: 1,
    borderColor: COLORS.info,
  },
  initiatedText: {
    ...FONTS.caption,
    color: COLORS.info,
    marginLeft: 4,
    fontWeight: "600",
  },
  notStartedBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.inputBackground,
    paddingHorizontal: SIZES.padding.sm,
    paddingVertical: 4,
    borderRadius: SIZES.radius.sm,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  notStartedText: {
    ...FONTS.caption,
    color: COLORS.textSecondary,
    marginLeft: 4,
    fontWeight: "600",
  },
  statusMessages: {
    marginTop: SIZES.margin.xs,
  },
  aadhaarNote: {
    ...FONTS.caption,
    color: COLORS.textSecondary,
    marginTop: SIZES.margin.xs,
    fontStyle: "italic",
  },
  infoNote: {
    ...FONTS.caption,
    color: COLORS.info,
    fontStyle: "italic",
  },
  successNote: {
    ...FONTS.caption,
    color: COLORS.success,
    fontWeight: "600",
  },
  errorNote: {
    ...FONTS.caption,
    color: COLORS.error,
    fontStyle: "italic",
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: SIZES.padding.lg,
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderRadius: SIZES.radius.xl,
    padding: SIZES.padding.lg,
    width: "100%",
    maxWidth: 400,
  },
  detailsModalContent: {
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SIZES.margin.lg,
  },
  modalTitle: {
    ...FONTS.h5,
    color: COLORS.textPrimary,
    flex: 1,
  },
  selectedDatePreview: {
    ...FONTS.body,
    color: COLORS.primary,
    textAlign: "center",
    marginBottom: SIZES.margin.lg,
    fontWeight: "600",
  },
  pickerContainer: {
    flexDirection: "row",
    height: 200,
    marginBottom: SIZES.margin.lg,
  },
  pickerColumn: {
    flex: 1,
    marginHorizontal: SIZES.margin.xs,
  },
  pickerLabel: {
    ...FONTS.label,
    color: COLORS.textPrimary,
    textAlign: "center",
    marginBottom: SIZES.margin.sm,
    fontWeight: "600",
  },
  pickerScrollView: {
    flex: 1,
  },
  pickerItem: {
    paddingVertical: SIZES.padding.sm,
    paddingHorizontal: SIZES.padding.xs,
    borderRadius: SIZES.radius.sm,
    marginVertical: 2,
    alignItems: "center",
  },
  pickerItemSelected: {
    backgroundColor: COLORS.primary,
  },
  pickerItemText: {
    ...FONTS.body,
    color: COLORS.textSecondary,
  },
  pickerItemTextSelected: {
    color: COLORS.white,
    fontWeight: "600",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: SIZES.margin.lg,
  },
  wideButton: {
    flex: 1,
    marginHorizontal: SIZES.margin.xs,
  },
  cancelButton: {
    height: SIZES.button.md,
    backgroundColor: COLORS.inputBackground,
    borderRadius: SIZES.radius.md,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: SIZES.padding.md,
  },
  cancelButtonText: {
    ...FONTS.button,
    color: COLORS.textSecondary,
  },
  setButton: {
    height: SIZES.button.md,
    backgroundColor: COLORS.primary,
    borderRadius: SIZES.radius.md,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: SIZES.padding.md,
  },
  setButtonText: {
    ...FONTS.button,
    color: COLORS.white,
  },
  // Aadhaar details modal styles
  detailsScrollView: {
    maxHeight: 300,
  },
  detailsSection: {
    marginBottom: SIZES.margin.lg,
  },
  detailsSectionTitle: {
    ...FONTS.h6,
    color: COLORS.primary,
    marginBottom: SIZES.margin.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
    paddingBottom: SIZES.padding.xs,
  },
  detailRow: {
    flexDirection: "row",
    marginBottom: SIZES.margin.sm,
  },
  detailLabel: {
    ...FONTS.body,
    color: COLORS.textSecondary,
    width: 120,
    fontWeight: "600",
  },
  detailValue: {
    ...FONTS.body,
    color: COLORS.textPrimary,
    flex: 1,
  },
  modalQuestion: {
    ...FONTS.body,
    color: COLORS.textPrimary,
    textAlign: "center",
    marginVertical: SIZES.margin.lg,
    fontWeight: "600",
  },
});