// styles.js
import { StyleSheet, Platform } from "react-native";
import { SHADOWS, COLORS, SIZES, FONTS } from "../../utils/AppTheme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  loadingText: {
    ...FONTS.body,
    color: COLORS.textSecondary,
    marginTop: SIZES.margin.md,
  },
  scrollContent: {
    padding: SIZES.padding.lg,
  },
  header: {
    backgroundColor: COLORS.primary,
    padding: SIZES.padding.lg,
    borderRadius: SIZES.radius.lg,
    alignItems: "center",
    marginBottom: SIZES.margin.lg,
    position: "relative",
    ...SHADOWS.md,
  },
  backBtn: {
    position: "absolute",
    left: SIZES.padding.lg,
    top: SIZES.padding.lg,
    zIndex: 1,
  },
  clearBtn: {
    position: "absolute",
    right: SIZES.padding.lg,
    top: SIZES.padding.lg,
    backgroundColor: COLORS.primaryDark,
    padding: SIZES.padding.xs,
    borderRadius: SIZES.radius.full,
    zIndex: 1,
  },
  headerTitle: {
    ...FONTS.h4,
    color: COLORS.white,
    marginTop: SIZES.margin.sm,
    textAlign: "center",
  },
  headerSubtitle: {
    ...FONTS.bodySmall,
    color: COLORS.white,
    marginTop: SIZES.margin.xs,
    textAlign: "center",
  },
  section: {
    backgroundColor: COLORS.white,
    borderRadius: SIZES.radius.lg,
    padding: SIZES.padding.lg,
    marginBottom: SIZES.margin.lg,
    ...SHADOWS.sm,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  sectionTitle: {
    ...FONTS.h5,
    color: COLORS.textPrimary,
    marginBottom: SIZES.margin.md,
  },
  subSectionTitle: {
    ...FONTS.h6,
    color: COLORS.textSecondary,
    marginBottom: SIZES.margin.sm,
    marginTop: SIZES.margin.md,
    fontWeight: "600",
  },
  autoFillTitle: {
    ...FONTS.h6,
    color: COLORS.success,
    marginBottom: SIZES.margin.sm,
    marginTop: SIZES.margin.md,
    fontWeight: "600",
  },
  optionalNote: {
    ...FONTS.caption,
    color: COLORS.textSecondary,
    fontStyle: "italic",
    marginBottom: SIZES.margin.md,
  },
  input1: {
    height: SIZES.input.height,
    backgroundColor: COLORS.inputBackground,
    borderRadius: SIZES.radius.md,
    paddingHorizontal: SIZES.padding.xl,
    ...FONTS.body,
    color: COLORS.textPrimary,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    flexDirection: "row",
    alignItems: "center",
  },
  inputGroup: {
    marginBottom: SIZES.margin.md,
  },
  label: {
    ...FONTS.label,
    color: COLORS.textPrimary,
    marginBottom: SIZES.margin.xs,
  },
  input: {
    height: SIZES.input.height,
    backgroundColor: COLORS.inputBackground,
    borderRadius: SIZES.radius.md,
    paddingHorizontal: SIZES.padding.md,
    ...FONTS.body,
    color: COLORS.textPrimary,
    borderWidth: 1.5,
    borderColor: COLORS.border,
  },
  errorInput: {
    borderColor: COLORS.error,
    borderWidth: 2,
  },
  dateText: {
    ...FONTS.body,
    color: COLORS.textPrimary,
    flex: 1,
  },
  placeholderText: {
    ...FONTS.body,
    color: COLORS.inputPlaceholder,
    flex: 1,
  },
  dateIcon: {
    marginLeft: SIZES.margin.sm,
  },
  checkboxContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: SIZES.margin.xs,
  },
  checkbox: {
    flex: 1,
    height: SIZES.input.height,
    backgroundColor: COLORS.inputBackground,
    borderRadius: SIZES.radius.md,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: SIZES.margin.xs,
  },
  checkboxSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primaryDark,
  },
  checkboxText: {
    ...FONTS.body,
    color: COLORS.textSecondary,
  },
  checkboxTextSelected: {
    color: COLORS.white,
    fontWeight: "600",
  },
  mobileInput: {
    flexDirection: "row",
    alignItems: "center",
    height: SIZES.input.height,
    backgroundColor: COLORS.inputBackground,
    borderRadius: SIZES.radius.md,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    paddingHorizontal: SIZES.padding.md,
  },
  countryCode: {
    ...FONTS.h6,
    color: COLORS.primary,
    marginRight: SIZES.margin.sm,
  },
  mobileField: {
    flex: 1,
    ...FONTS.body,
    color: COLORS.textPrimary,
  },
  errorText: {
    ...FONTS.caption,
    color: COLORS.error,
    marginTop: SIZES.margin.xs,
  },
  infoText: {
    ...FONTS.caption,
    color: COLORS.info,
    marginTop: SIZES.margin.xs,
    fontStyle: "italic",
  },
  successText: {
    ...FONTS.caption,
    color: COLORS.success,
    marginTop: SIZES.margin.xs,
    fontWeight: "600",
  },
  confirmBtn: {
    backgroundColor: COLORS.primary,
    height: SIZES.button.lg,
    borderRadius: SIZES.radius.lg,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: SIZES.margin.xl,
    ...SHADOWS.md,
  },
  confirmBtnDisabled: {
    backgroundColor: COLORS.disabled,
  },
  confirmText: {
    ...FONTS.button,
    color: COLORS.white,
  },
  // Aadhaar specific styles
  aadhaarContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  aadhaarInput: {
    flex: 1,
    marginRight: SIZES.margin.sm,
  },
  verifyButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: SIZES.padding.md,
    paddingVertical: SIZES.padding.sm,
    borderRadius: SIZES.radius.md,
    minWidth: 80,
    alignItems: "center",
  },
  verifyButtonText: {
    ...FONTS.bodySmall,
    color: COLORS.white,
    fontWeight: "600",
  },
  verificationStatus: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: SIZES.margin.xs,
  },
  verifyingText: {
    ...FONTS.caption,
    color: COLORS.info,
    marginLeft: SIZES.margin.xs,
  },
  // Consent Modal Styles
  consentModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: SIZES.padding.lg,
  },
  consentModalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    width: "100%",
    maxWidth: 400,
    maxHeight: "80%",
    overflow: "hidden",
    ...SHADOWS.lg,
  },
  consentModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
    position: "relative",
  },
  consentModalTitle: {
    ...FONTS.h5,
    color: COLORS.textPrimary,
    marginLeft: 12,
    flex: 1,
  },
  consentModalClose: {
    padding: 4,
  },
  consentModalBody: {
    padding: 20,
  },
  consentModalButtons: {
    flexDirection: "row",
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
  },
  consentCancelButton: {
    flex: 1,
    padding: 14,
    backgroundColor: COLORS.inputBackground,
    borderRadius: 10,
    alignItems: "center",
    marginRight: 10,
  },
  consentCancelButtonText: {
    ...FONTS.body,
    color: COLORS.textSecondary,
    fontWeight: "600",
  },
  consentConfirmButton: {
    flex: 1,
    padding: 14,
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  consentConfirmButtonText: {
    ...FONTS.body,
    color: COLORS.white,
    fontWeight: "600",
    marginLeft: 8,
  },
  // Consent Form Specific Styles
  consentTitle: {
    ...FONTS.h6,
    color: COLORS.primary,
    marginBottom: 16,
    textAlign: "center",
    fontWeight: "600",
  },
  consentText: {
    ...FONTS.bodySmall,
    color: COLORS.textPrimary,
    marginBottom: 12,
    lineHeight: 20,
  },
  aadhaarComparisonContainer: {
    backgroundColor: COLORS.inputBackground,
    padding: 16,
    borderRadius: 8,
    marginVertical: 16,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  comparisonTitle: {
    ...FONTS.label,
    color: COLORS.textPrimary,
    marginBottom: 12,
    fontWeight: "600",
  },
  comparisonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  comparisonLabel: {
    ...FONTS.bodySmall,
    color: COLORS.textSecondary,
  },
  comparisonValue: {
    ...FONTS.bodySmall,
    color: COLORS.textPrimary,
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
    fontWeight: "600",
  },
  aadhaarWarning: {
    ...FONTS.caption,
    color: COLORS.error,
    marginTop: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  confirmationCheckboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.inputBackground,
    padding: 12,
    borderRadius: 8,
    marginTop: 16,
    marginBottom: 8,
  },
  checkboxIconContainer: {
    marginRight: 10,
  },
  confirmationText: {
    ...FONTS.bodySmall,
    color: COLORS.textPrimary,
    flex: 1,
    lineHeight: 20,
  },
  consentConfirmButtonDisabled: {
    backgroundColor: COLORS.disabled,
    opacity: 0.7,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: SIZES.padding.lg,
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderRadius: SIZES.radius.xl,
    padding: SIZES.padding.lg,
    width: "100%",
    maxWidth: 400,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SIZES.margin.lg,
  },
  modalTitle: {
    ...FONTS.h5,
    color: COLORS.textPrimary,
    flex: 1,
  },
  selectedDatePreview: {
    ...FONTS.body,
    color: COLORS.primary,
    textAlign: "center",
    marginBottom: SIZES.margin.lg,
    fontWeight: "600",
  },
  pickerContainer: {
    flexDirection: "row",
    height: 200,
    marginBottom: SIZES.margin.lg,
  },
  pickerColumn: {
    flex: 1,
    marginHorizontal: SIZES.margin.xs,
  },
  pickerLabel: {
    ...FONTS.label,
    color: COLORS.textPrimary,
    textAlign: "center",
    marginBottom: SIZES.margin.sm,
    fontWeight: "600",
  },
  pickerScrollView: {
    flex: 1,
  },
  pickerItem: {
    paddingVertical: SIZES.padding.sm,
    paddingHorizontal: SIZES.padding.xs,
    borderRadius: SIZES.radius.sm,
    marginVertical: 2,
    alignItems: "center",
  },
  pickerItemSelected: {
    backgroundColor: COLORS.primary,
  },
  pickerItemText: {
    ...FONTS.body,
    color: COLORS.textSecondary,
  },
  pickerItemTextSelected: {
    color: COLORS.white,
    fontWeight: "600",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: SIZES.margin.lg,
  },
  cancelButton: {
    flex: 1,
    height: SIZES.button.md,
    backgroundColor: COLORS.inputBackground,
    borderRadius: SIZES.radius.md,
    justifyContent: "center",
    alignItems: "center",
    marginRight: SIZES.margin.sm,
  },
  cancelButtonText: {
    ...FONTS.button,
    color: COLORS.textSecondary,
  },
  setButton: {
    flex: 1,
    height: SIZES.button.md,
    backgroundColor: COLORS.primary,
    borderRadius: SIZES.radius.md,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: SIZES.margin.sm,
  },
  setButtonText: {
    ...FONTS.button,
    color: COLORS.white,
  },
  // WebView Styles
  webViewContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  webViewHeader: {
    backgroundColor: COLORS.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SIZES.padding.md,
    paddingVertical: SIZES.padding.sm,
    paddingTop: Platform.OS === "ios" ? SIZES.padding.xl : SIZES.padding.sm,
  },
  webViewBackButton: {
    flexDirection: "row",
    alignItems: "center",
  },
  webViewBackText: {
    ...FONTS.bodySmall,
    color: COLORS.white,
    marginLeft: SIZES.margin.xs,
  },
  webViewTitle: {
    ...FONTS.h6,
    color: COLORS.white,
    fontWeight: "600",
  },
  webViewPlaceholder: {
    width: 60,
  },
  webView: {
    flex: 1,
  },
  webViewLoading: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  webViewLoadingText: {
    ...FONTS.body,
    color: COLORS.textSecondary,
    marginTop: SIZES.margin.md,
  },
});